spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.mkjvmnlspgonxqodkjox
spring.datasource.password=ThreeFour123@#$

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Limit connections per tester
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
# Allow a longer wait time for a connection if the database is busy
spring.datasource.hikari.connection-timeout=30000